config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users
  resources :posts do
      resources :comments
  end
  root "posts#index"  
  get '/about', to: 'pages#about'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true
	validates :body, presence: true
	belongs_to :user
	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :post
	has_many :comment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	
	end
	def home
		@posts = Post.all
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    # before_action :authenticate_user, except |:index, :show|
    
    def index
    	@posts = Post.all.order('created_at DESC')
    end

    def new
      @post = Post.new
    end

    def create
    	@post = Post.new(post_params)
      if   @post.save
      	   redirect_to @post
      else
           render 'new'
    	# else
    	# 	render :new
    	# end
      end
    end

    def show
    	@post = Post.find(params[:id])
    end

    def edit
      @post = Post.find(params[:id])
    end
    def update
      @post = Post.find(params[:id])

      if @post.update(params[:post].permit(title: :body))
        redirect_to root_path
      else
        render 'edit'
      end
    end
def destroy
  @post = Post.find(params[:id])
  @post.destroy

  redirect_to posts_path
end

   private
     def post_params
     	params.require(:post).permit(:title, :kind, :body)
     end
 
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
	</div>




	
	<p><%= link_to 'Delete', [comment.post, comment],
								  method: :delete,
								  class: "button",
								 	data: { confirm: 'Are you sure?' } %></p>
 	
</div>

app/views/comments/_form.html.erb
<%= form_for ([@post, @post.comments.build]) do |f| %>
	<p>
		<%= f.label :name %> <br>
		<%= f.text_field :name %> <br>
	</p>
	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %><br>
	</p>
	<br>
	<p>
      <%= f.submit %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
		<head>
		  <title>Blog</title>
		  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
		  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	  	  <link href="css/bootstrap.min.css" rel="stylesheet">
	  	  <link href="css/stylish-portfolio.css" rel="stylesheet">
	  	  <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
	  	  <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
	  <%= csrf_meta_tags %>
		  <%= csrf_meta_tags %>
		</head>
<body>
		

	  <div class="container">
		    <div class="page-header">
			   <nav>
			   		
					<ul class="nav nav-pills pull-right">						
						<li><%= link_to "Blog", root_path %></li>
						<li><%= link_to "About", about_path %></li>
						
						<li class="button"><%= link_to "New Post", new_post_path %></li>
						<li class="button"><%= link_to "Log Out" ,destroy_user_session_path, method: :delete%></li>
						
					</ul>
					    
				</nav>
			 </div>
	  </div> 
	  <div>
			<% if current_page?(root_path) %>
					<p>All Posts</p>
				<% elsif current_page?(about_path) %>
					<p>About</p>
				<% else %>
					<%= link_to "Back to All Posts", root_path %>
				<% end %><br>
	  </div>


  <nav id="sidebar-wrapper" class="">
        <ul class="sidebar-nav">
            <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle">
            	<i class="fa fa-times">
            	</i>
            </a>

            <li class="sidebar-brand">                
            <ul class="">
				<li><a href="https://twitter.com/bloomfieldbam">Twitter</a></li>
				<li><a href="http://instagram.com/typestrange">Instagram</a></li>
				<li><a href="https://github.com/bamtype">Github</a></li>
				<li><a href="mailto:bamtype@gmail.com">Email</a></li>
			</ul>	
        </ul>
  </nav>
	 <a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle">
	 	<i class="fa fa-bars">
	 	</i>
	 </a>



   <!--  <div id="sidebar">
			<ul class="nav nav-pills pull left">
				<li><a href="https://twitter.com/bloomfieldbam">Twitter</a></li>
				<li><a href="http://instagram.com/typestrange">Instagram</a></li>
				<li><a href="https://github.com/bamtype">Github</a></li>
				<li><a href="mailto:bamtype@gmail.com">Email</a></li>
			</ul>			
	</div>  -->






		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert") %>
		<% end %>

			<div class="row">
			   <div class= "col-md-6 col-md-offset-3">
		     	 <%= yield %>
		       </div>  
		    </div>
	 </div>
	 <script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover(); 
});
</script>
 </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<p class="text-center"><strong>AmsterBam</strong></p>

	<div id="profile_image">		
		
	</div>
<img src="http://i.telegraph.co.uk/multimedia/archive/02089/underwear_2089018i.jpg" class="img-circle">
	<div id="content">
		<p class="text-center"><strong>Fuck yo' Couch</strong></p>
		
		<!-- <a href="#" data-toggle="popover" title="Open is you are a mudderscunt" data-content="Syou were whether you clicked or not">I love to Cha Cha</a> -->

		<p>

			Brothers tried and others died to get the formula
			But I'mma let you sweat, you still ain't formed, you a
			Step away from frozen, stiff as if you're posing
			Dig into my brain as the rhyme gets chosen
			Sobamtype follow me and while you're thinking you were first
			Let's travel at magnificent speeds around the universe
			What could you say as the earth gets further and further away
			Planets as small as balls of clay
			Astray into the milky way, worlds out of sight
			Far as the eye can see not even a satellite
			Now stop and turn around and look
			As you stare in the darkness, your knowledge is took
			So keep staring, soon you suddenly see a star
			You better follow it, cause it's the R
			This is a lesson if you're guessing and if you're borrowing
			Hurry hurry step right up and keep following the leader

		</p>
		<p>
			If you'd like to follow along as I hip you to some game conteact me at<a href="http://twitter.com/bloomfieldbam">@bamtype@gmail.com
		</p>
	</div>
</div>
<script>




</script>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>

	<div =id"errors">
		<h2>
			<%= pluralize(@post.errors.count, "error") %> prevented this post from saving
	    </h2>

		<ul>
	      <% @post.errors.full_messages.each do |msg| %>
			   <li><%= msg %></li>
		  <% end %>
	    </ul>

    </div>

		<% end %>
	 <div class="form-group">
	    <%= f.label :title %><br>
	    <%= f.text_field :title, class: "form-control" %>
	  </div>

	  <div class="form-group">
	     <%= f.label :kind %><br>
	     <%= f.select :kind,  ["text","image url"], {}, class: "form-control" %> 
      </div>

	  <div class="form-group">
	    <%= f.label :body %><br>
	    <%= f.text_area :body, :rows=>10, class: "form-control" %>
	  </div>

	<div class="form-group">
	    <%= f.submit "Submit", class: "btn btn-primary" %>
	  </div>
	<% end %>

	<p>TYPE:STRANGE</p>
	

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>

<div class="post-wrapper">

	<tbody>
		<h2 class="title">

			<%= link_to post.title, post %> 
		</h2>
		<tr>
			<td><%= truncate(post.body, length: 50) %></td>
		</tr>
		<p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
	</tbody>
	
</div> 

<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>New Post</h1>

	<%= render 'form' %>

	<%= link_to 'Back', posts_path %> 
</div>

app/views/posts/show.html.erb
<div id="post_content">

	<h1 class="title">
		<%= @post.title %>
	</h1>

	<p class="date">
		Submitted <%= time_ago_in_words(@post.created_at) %> Ago
		<% if user_signed_in? %>		
		| <%= link_to 'Edit', edit_post_path(@post) %>
		| <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>
	</p>


	<p class="body">
		<%= @post.body %>
		<%= render 'post', post: @post%>
	</p>
	<div id="comments">
		<h2><%= @post.comments.count %> Comments </h2>
		<%= render @post.comments %>

		<h3>Add a comment</h3>
		<%= render "comments/form" %>
	</div>
</div>